name: Permission check
on:
  pull_request:
    paths:
      - '**/run'
      - '**/finish'
jobs:
  permission_check:
    runs-on: ubuntu-latest
    uses: aptalca/testing/.github/workflows/init-svc-executable-permissions.yml@master
