name: Issue & PR Tracker

on:
  issues:
    types: [opened,closed,reopened,labeled,unlabeled]
  pull_request:
    types: [opened,closed,reopened,review_requested,review_request_removed,labeled,unlabeled]
  pull_request_target:
    types: [opened,closed,reopened,review_requested,review_request_removed,labeled,unlabeled]

jobs:
  Add New Issue:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        if: ${{ github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened' }}
        with:
          project: Issue & PR Tracker
          column: Issues
          repo-token: ${{ secrets.GITHUB_TOKEN }}