name: Issue & PR Tracker

on:
  issues:
    types: [opened,closed,reopened,labeled,unlabeled]
  pull_request:
    types: [opened,closed,reopened,review_requested,review_request_removed,labeled,unlabeled]
  pull_request_target:
    types: [opened,closed,reopened,review_requested,review_request_removed,labeled,unlabeled]

jobs:
  add-new-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        if: ${{ github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened') }}
        with:
          ghtoken: ${{ secrets.PROJECT_PAT }}
          user: aptalca
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: test