name: Issue & PR Tracker

on:
  issues:
    types: [opened,reopened,labeled,unlabeled]
  pull_request_target:
    types: [opened,reopened,review_requested,review_request_removed,labeled,unlabeled]

jobs:
  manage-project:
    uses: aptalca/test/.github/workflows/callable_issue_pr_tracker.yml@master
    secrets: inherit
