name: Issue & PR Tracker

on:
  issues:
    types: [opened,reopened,labeled,unlabeled]
  pull_request:
    types: [opened,reopened,review_requested,review_request_removed,labeled,unlabeled]

jobs:
  manage-project:
    runs-on: ubuntu-latest
    steps:
      - name: Dump payload info
        uses: Dovyski/payload-info-action@master
        with:
          filter_push: '.'
          filter_pull_request: '.pull_request'
      - name: Add New or Reopened Issues
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        if: ${{ github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened') }}
        with:
          gh_token: ${{ secrets.PROJECT_PAT }}
          user: aptalca
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: 'Issues'
      - name: Add New or Reopened PRs Without Review Requests
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        if: ${{ (github.event.action == 'opened' || github.event.action == 'reopened') && github.event_name == 'pull_request' && github.event.pull_request.requested_reviewers == '[]' && github.event.pull_request.requested_teams == '[]' }}
        with:
          gh_token: ${{ secrets.PROJECT_PAT }}
          user: aptalca
          project_id: 2
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: 'PRs'
